---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
      app.kubernetes.io/instance: inventory
      app.kubernetes.io/component: service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory
        app.kubernetes.io/instance: inventory
        app.kubernetes.io/component: service
    spec:
      containers:
        - name: inventory
          image: registry.hochschule-burgenland.muehlbachler.xyz/swm2-ws2025-group-a-inventory/inventory:v1.0.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: inventory-service-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: inventory-service-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-service-config
                  key: DB_PASSWORD
            - name: EXTERNAL_SERVICE_NAME_1
              valueFrom:
                secretKeyRef:
                  name: inventory-service-config
                  key: EXT_SERVICE_NAME_1
            - name: EXTERNAL_SERVICE_NAME_2
              valueFrom:
                secretKeyRef:
                  name: inventory-service-config
                  key: EXT_SERVICE_NAME_2
            - name: EXTERNAL_SERVICE_URL_1
              valueFrom:
                secretKeyRef:
                  name: inventory-service-config
                  key: EXT_SERVICE_URL_1
            - name: EXTERNAL_SERVICE_URL_2
              valueFrom:
                secretKeyRef:
                  name: inventory-service-config
                  key: EXT_SERVICE_URL_2
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                secretKeyRef:
                  name: inventory-service-config
                  key: JAVA_TOOL_OPTIONS
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: registry-credentials
